all: 
	cd bgdc; $(MAKE) -f Makefile
	cd bgdrtm; $(MAKE) -f Makefile
	cd bgdi; $(MAKE) -f Makefile

linux:
	cd bgdc; $(MAKE) -f Makefile.linux
	cd bgdrtm; $(MAKE) -f Makefile.linux
	cd bgdi; $(MAKE) -f Makefile.linux

clean:
	./clean
