#!/bin/sh

if [ -x "`which gfind`" ]; then
	FIND=gfind;
	echo "Using GNU find"
else
	FIND=find;
fi

cd ..

for i in $($FIND -iname *.o); do rm $i; done
for i in $($FIND -iname *.d); do rm $i; done
for i in $($FIND -iname *.a); do rm $i; done
for i in $($FIND -iname *.elf); do rm $i; done
for i in $($FIND -iname *.dol); do rm $i; done
for i in $($FIND -iname *.PBP); do rm $i; done
for i in $($FIND -iname *.SFO); do rm $i; done

cd -
