# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_mainwindow.ui'
#
# Created: Sun May  5 01:44:02 2013
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(966, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("res/icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_appfiles = QtGui.QLabel(self.centralwidget)
        self.label_appfiles.setObjectName(_fromUtf8("label_appfiles"))
        self.verticalLayout_2.addWidget(self.label_appfiles)
        self.filelist = QtGui.QListWidget(self.centralwidget)
        self.filelist.setObjectName(_fromUtf8("filelist"))
        self.verticalLayout_2.addWidget(self.filelist)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_appOSselector = QtGui.QLabel(self.centralwidget)
        self.label_appOSselector.setObjectName(_fromUtf8("label_appOSselector"))
        self.horizontalLayout_3.addWidget(self.label_appOSselector)
        self.appOSselector = QtGui.QComboBox(self.centralwidget)
        self.appOSselector.setEnabled(False)
        self.appOSselector.setObjectName(_fromUtf8("appOSselector"))
        self.appOSselector.addItem(_fromUtf8(""))
        self.horizontalLayout_3.addWidget(self.appOSselector)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.line_appdir = QtGui.QLineEdit(self.centralwidget)
        self.line_appdir.setEnabled(False)
        self.line_appdir.setObjectName(_fromUtf8("line_appdir"))
        self.horizontalLayout_7.addWidget(self.line_appdir)
        self.button_appdirselector = QtGui.QPushButton(self.centralwidget)
        self.button_appdirselector.setObjectName(_fromUtf8("button_appdirselector"))
        self.horizontalLayout_7.addWidget(self.button_appdirselector)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_applabel = QtGui.QLabel(self.centralwidget)
        self.label_applabel.setObjectName(_fromUtf8("label_applabel"))
        self.horizontalLayout_4.addWidget(self.label_applabel)
        self.line_applabel = QtGui.QLineEdit(self.centralwidget)
        self.line_applabel.setEnabled(True)
        self.line_applabel.setStatusTip(_fromUtf8(""))
        self.line_applabel.setText(_fromUtf8(""))
        self.line_applabel.setReadOnly(False)
        self.line_applabel.setObjectName(_fromUtf8("line_applabel"))
        self.horizontalLayout_4.addWidget(self.line_applabel)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_appname = QtGui.QLabel(self.centralwidget)
        self.label_appname.setObjectName(_fromUtf8("label_appname"))
        self.horizontalLayout_5.addWidget(self.label_appname)
        self.line_appname = QtGui.QLineEdit(self.centralwidget)
        self.line_appname.setObjectName(_fromUtf8("line_appname"))
        self.horizontalLayout_5.addWidget(self.line_appname)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_orientation = QtGui.QLabel(self.centralwidget)
        self.label_orientation.setObjectName(_fromUtf8("label_orientation"))
        self.horizontalLayout_9.addWidget(self.label_orientation)
        self.combo_orientation = QtGui.QComboBox(self.centralwidget)
        self.combo_orientation.setObjectName(_fromUtf8("combo_orientation"))
        self.combo_orientation.addItem(_fromUtf8(""))
        self.combo_orientation.addItem(_fromUtf8(""))
        self.horizontalLayout_9.addWidget(self.combo_orientation)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.check_admob = QtGui.QCheckBox(self.centralwidget)
        self.check_admob.setObjectName(_fromUtf8("check_admob"))
        self.horizontalLayout_10.addWidget(self.check_admob)
        self.line_admob = QtGui.QLineEdit(self.centralwidget)
        self.line_admob.setEnabled(False)
        self.line_admob.setReadOnly(False)
        self.line_admob.setObjectName(_fromUtf8("line_admob"))
        self.horizontalLayout_10.addWidget(self.line_admob)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.label_icons = QtGui.QLabel(self.centralwidget)
        self.label_icons.setObjectName(_fromUtf8("label_icons"))
        self.verticalLayout.addWidget(self.label_icons)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.icon_xhdpi = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.icon_xhdpi.sizePolicy().hasHeightForWidth())
        self.icon_xhdpi.setSizePolicy(sizePolicy)
        self.icon_xhdpi.setMinimumSize(QtCore.QSize(96, 96))
        self.icon_xhdpi.setMaximumSize(QtCore.QSize(96, 96))
        self.icon_xhdpi.setText(_fromUtf8(""))
        self.icon_xhdpi.setIcon(icon)
        self.icon_xhdpi.setIconSize(QtCore.QSize(96, 96))
        self.icon_xhdpi.setFlat(True)
        self.icon_xhdpi.setObjectName(_fromUtf8("icon_xhdpi"))
        self.horizontalLayout_8.addWidget(self.icon_xhdpi)
        self.icon_hdpi = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.icon_hdpi.sizePolicy().hasHeightForWidth())
        self.icon_hdpi.setSizePolicy(sizePolicy)
        self.icon_hdpi.setMinimumSize(QtCore.QSize(72, 72))
        self.icon_hdpi.setMaximumSize(QtCore.QSize(72, 72))
        self.icon_hdpi.setText(_fromUtf8(""))
        self.icon_hdpi.setIcon(icon)
        self.icon_hdpi.setIconSize(QtCore.QSize(72, 72))
        self.icon_hdpi.setFlat(True)
        self.icon_hdpi.setObjectName(_fromUtf8("icon_hdpi"))
        self.horizontalLayout_8.addWidget(self.icon_hdpi)
        self.icon_mdpi = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(48)
        sizePolicy.setVerticalStretch(48)
        sizePolicy.setHeightForWidth(self.icon_mdpi.sizePolicy().hasHeightForWidth())
        self.icon_mdpi.setSizePolicy(sizePolicy)
        self.icon_mdpi.setMinimumSize(QtCore.QSize(48, 48))
        self.icon_mdpi.setMaximumSize(QtCore.QSize(48, 49))
        self.icon_mdpi.setText(_fromUtf8(""))
        self.icon_mdpi.setIcon(icon)
        self.icon_mdpi.setIconSize(QtCore.QSize(48, 48))
        self.icon_mdpi.setFlat(True)
        self.icon_mdpi.setObjectName(_fromUtf8("icon_mdpi"))
        self.horizontalLayout_8.addWidget(self.icon_mdpi)
        self.icon_ldpi = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(32)
        sizePolicy.setVerticalStretch(32)
        sizePolicy.setHeightForWidth(self.icon_ldpi.sizePolicy().hasHeightForWidth())
        self.icon_ldpi.setSizePolicy(sizePolicy)
        self.icon_ldpi.setMinimumSize(QtCore.QSize(32, 32))
        self.icon_ldpi.setMaximumSize(QtCore.QSize(32, 32))
        self.icon_ldpi.setText(_fromUtf8(""))
        self.icon_ldpi.setIcon(icon)
        self.icon_ldpi.setIconSize(QtCore.QSize(32, 32))
        self.icon_ldpi.setFlat(True)
        self.icon_ldpi.setObjectName(_fromUtf8("icon_ldpi"))
        self.horizontalLayout_8.addWidget(self.icon_ldpi)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_debug = QtGui.QLabel(self.centralwidget)
        self.label_debug.setObjectName(_fromUtf8("label_debug"))
        self.horizontalLayout_2.addWidget(self.label_debug)
        self.combo_debug = QtGui.QComboBox(self.centralwidget)
        self.combo_debug.setObjectName(_fromUtf8("combo_debug"))
        self.combo_debug.addItem(_fromUtf8(""))
        self.combo_debug.addItem(_fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.combo_debug)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.check_install = QtGui.QCheckBox(self.centralwidget)
        self.check_install.setChecked(True)
        self.check_install.setObjectName(_fromUtf8("check_install"))
        self.horizontalLayout_6.addWidget(self.check_install)
        self.button_package = QtGui.QPushButton(self.centralwidget)
        self.button_package.setObjectName(_fromUtf8("button_package"))
        self.horizontalLayout_6.addWidget(self.button_package)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 966, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuEmulator = QtGui.QMenu(self.menubar)
        self.menuEmulator.setObjectName(_fromUtf8("menuEmulator"))
        self.menuAVD = QtGui.QMenu(self.menuEmulator)
        self.menuAVD.setObjectName(_fromUtf8("menuAVD"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionPreferences = QtGui.QAction(MainWindow)
        self.actionPreferences.setObjectName(_fromUtf8("actionPreferences"))
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionAndroid = QtGui.QAction(MainWindow)
        self.actionAndroid.setObjectName(_fromUtf8("actionAndroid"))
        self.actionSDK_Manager = QtGui.QAction(MainWindow)
        self.actionSDK_Manager.setObjectName(_fromUtf8("actionSDK_Manager"))
        self.actionAVD_Manager = QtGui.QAction(MainWindow)
        self.actionAVD_Manager.setObjectName(_fromUtf8("actionAVD_Manager"))
        self.actionDDMS = QtGui.QAction(MainWindow)
        self.actionDDMS.setObjectName(_fromUtf8("actionDDMS"))
        self.menuFile.addAction(self.actionPreferences)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuEmulator.addAction(self.menuAVD.menuAction())
        self.menuEmulator.addSeparator()
        self.menuEmulator.addAction(self.actionSDK_Manager)
        self.menuEmulator.addAction(self.actionAVD_Manager)
        self.menuEmulator.addAction(self.actionDDMS)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEmulator.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "BennuGD Packager", None))
        self.label_appfiles.setText(_translate("MainWindow", "Detected game files:", None))
        self.filelist.setToolTip(_translate("MainWindow", "<html><head/><body><p>The list of files that will get packed.</p><p>Please note that some files (*.exe, *.dll...) will not actually be copied.</p></body></html>", None))
        self.label_appOSselector.setText(_translate("MainWindow", "Target OS:", None))
        self.appOSselector.setToolTip(_translate("MainWindow", "The OS you\'re packaging your app for", None))
        self.appOSselector.setItemText(0, _translate("MainWindow", "Android", None))
        self.line_appdir.setPlaceholderText(_translate("MainWindow", "Please choose a dir", None))
        self.button_appdirselector.setText(_translate("MainWindow", "Select game directory...", None))
        self.label_applabel.setText(_translate("MainWindow", "App descriptor:", None))
        self.line_applabel.setToolTip(_translate("MainWindow", "<html><head/><body><p>Unique ID for your app, should include your company\'s name and you game\'s name.</p></body></html>", None))
        self.line_applabel.setPlaceholderText(_translate("MainWindow", "com.yourcompany.gamename", None))
        self.label_appname.setText(_translate("MainWindow", "App name:", None))
        self.line_appname.setToolTip(_translate("MainWindow", "User-visible name for your app", None))
        self.line_appname.setPlaceholderText(_translate("MainWindow", "Name to be shown to the user", None))
        self.label_orientation.setText(_translate("MainWindow", "Orientation:", None))
        self.combo_orientation.setItemText(0, _translate("MainWindow", "Portrait", None))
        self.combo_orientation.setItemText(1, _translate("MainWindow", "Landscape", None))
        self.check_admob.setText(_translate("MainWindow", "Show AdMob ads:", None))
        self.line_admob.setPlaceholderText(_translate("MainWindow", "AdMob publisher ID", None))
        self.label_icons.setText(_translate("MainWindow", "Icons:", None))
        self.icon_xhdpi.setToolTip(_translate("MainWindow", "Icon for high resolution displays", None))
        self.icon_hdpi.setToolTip(_translate("MainWindow", "Icon for high resolution displays", None))
        self.icon_mdpi.setToolTip(_translate("MainWindow", "Icon for medium resolution displays", None))
        self.icon_ldpi.setToolTip(_translate("MainWindow", "Icon for low resolution displays", None))
        self.label_debug.setText(_translate("MainWindow", "Package for:", None))
        self.combo_debug.setToolTip(_translate("MainWindow", "Choose if you want to package for debug or for release", None))
        self.combo_debug.setItemText(0, _translate("MainWindow", "Debug", None))
        self.combo_debug.setItemText(1, _translate("MainWindow", "Release", None))
        self.check_install.setToolTip(_translate("MainWindow", "Install resulting APK to device or emulator", None))
        self.check_install.setText(_translate("MainWindow", "Install APK", None))
        self.button_package.setToolTip(_translate("MainWindow", "Click when you feel ready to package your app", None))
        self.button_package.setText(_translate("MainWindow", "Package && Install", None))
        self.menuFile.setTitle(_translate("MainWindow", "&File", None))
        self.menuEmulator.setTitle(_translate("MainWindow", "&Android", None))
        self.menuAVD.setTitle(_translate("MainWindow", "AVD", None))
        self.actionPreferences.setText(_translate("MainWindow", "Preferences", None))
        self.actionPreferences.setToolTip(_translate("MainWindow", "Preferences dialog", None))
        self.actionPreferences.setShortcut(_translate("MainWindow", "Ctrl+,", None))
        self.actionQuit.setText(_translate("MainWindow", "Quit", None))
        self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+Q", None))
        self.actionAndroid.setText(_translate("MainWindow", "Android", None))
        self.actionSDK_Manager.setText(_translate("MainWindow", "SDK Manager", None))
        self.actionSDK_Manager.setToolTip(_translate("MainWindow", "Launch the Android SDK manager", None))
        self.actionAVD_Manager.setText(_translate("MainWindow", "AVD Manager", None))
        self.actionAVD_Manager.setToolTip(_translate("MainWindow", "Launch the android AVD manager", None))
        self.actionDDMS.setText(_translate("MainWindow", "Monitor", None))
        self.actionDDMS.setToolTip(_translate("MainWindow", "Launch Android Monitor", None))

